### ISSUE TITLE
Kim todo List

### ISSUE THREAD

**Issue by KimMaru10** [KKimjinoh/hallym-festival-2024-frontEnd#58]
- [x] 라인업 페이지 
- [x] 부스 안내 데이터 입력 
- [x] 무대 안내 데이터 입력 
- [x] 기담 안내 데이터 입력 
- [x] 굿즈 / 이벤트 데이터 입력
- [x] 빙고 게임 디자인 수정
